languageCode = "en-us"
title = "Projecten"
baseURL = "https://ruben-e.github.io/projectportaal/"
theme = "site"

[taxonomies]
    werknemer = "werknemers"
    technologie = "technologieen"
    klant = "klanten"

[[menu.main]]
    name = "projecten"
    weight = -110
    identifier = "projecten"
    url = "/"
[[menu.main]]
    name = "klanten"
    weight = -100
    url = "/klanten/"
[[menu.main]]
    name = "collega's"
    weight = -90
    url = "/werknemers/"